#!/usr/bin/env python3
"""Build a planning package (agent instructions + a city's must-haves) and
write it into the city's itinerary markdown file.

Usage: python3 generate.py [city]      (default: mexico_city)

The package lives between BEGIN/END markers at the top of {city}_itinerary.md.
Re-running replaces only that block, so an itinerary written below it is kept.
"""
import difflib
import os
import re
import sys
from pathlib import Path
from dotenv import load_dotenv
from google import genai
from groq import Groq
import logging

ROOT = Path(__file__).resolve().parent
load_dotenv(ROOT / ".env")
DESTINATIONS = ROOT / "destinations"
INSTRUCTIONS = ROOT / "agent_instructions.md"
OUTPUT_DIR = ROOT / "output"  # == /app/output when run in the Docker image (WORKDIR /app)
BEGIN = "<!-- BEGIN TRAVEL-CONCIERGE PACKAGE (generated by generate.py; do not edit) -->"
END = "<!-- END TRAVEL-CONCIERGE PACKAGE -->"
GROQ_MODEL = "openai/gpt-oss-120b"  # fallback engine when Gemini is unavailable

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


def list_cities():
    if not DESTINATIONS.is_dir():
        sys.exit(f"Destinations folder not found: {DESTINATIONS}")
    return sorted(p.name for p in DESTINATIONS.iterdir() if p.is_dir())


def read_file(path, label):
    if not path.is_file():
        sys.exit(f"{label} not found: {path}")
    return path.read_text(encoding="utf-8").strip()


def itinerary_path(city):
    """{city}_itinerary.md in OUTPUT_DIR, or an existing similar file there
    (e.g. mexico_itinerary.md) or in ROOT (for backward compatibility)."""
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    for name in (city, city.split("_")[0]):
        for base in (OUTPUT_DIR, ROOT):
            path = base / f"{name}_itinerary.md"
            if path.is_file():
                return path
    return OUTPUT_DIR / f"{city}_itinerary.md"


def build_package(city):
    instructions = read_file(INSTRUCTIONS, "agent_instructions.md")
    must_haves = read_file(DESTINATIONS / city / "must_haves.txt", f"must_haves.txt for '{city}'")
    title = city.replace("_", " ").title()
    return "\n".join([
        BEGIN,
        f"# Planning Package: {title}",
        "",
        "## 1. Agent Instructions",
        "",
        instructions,
        "",
        "## 2. User Requirements",
        "",
        f"Source: `destinations/{city}/must_haves.txt`",
        "",
        "```text",
        must_haves,
        "```",
        END,
    ])


def write_package(city, package):
    path = itinerary_path(city)
    existing = path.read_text(encoding="utf-8") if path.is_file() else ""
    start, stop = existing.find(BEGIN), existing.find(END)
    if start != -1 and stop > start:
        action = "Updated"
        new = existing[:start] + package + existing[stop + len(END):]
    elif existing:
        action = "Added package to"
        new = package + "\n\n---\n\n" + existing
    else:
        action = "Created"
        new = package + "\n"
    path.write_text(new, encoding="utf-8")
    return action, path


def _generate_content_gemini(client, prompt):
    """Calls Gemini."""
    return client.models.generate_content(
        model="gemini-3.5-flash",
        contents=prompt,
    )


def _generate_content_groq(prompt):
    """Fallback engine: calls Groq's hosted Llama 3.3 70B model."""
    api_key = os.environ.get("GROQ_API_KEY")
    if not api_key:
        raise RuntimeError(
            "Gemini is unavailable and GROQ_API_KEY is not set, so the Groq "
            "fallback cannot run. Set GROQ_API_KEY to enable the fallback."
        )
    groq_client = Groq(api_key=api_key)
    completion = groq_client.chat.completions.create(
        model=GROQ_MODEL,
        messages=[{"role": "user", "content": prompt}],
    )
    return completion.choices[0].message.content


def _generate_content(client, prompt):
    """Calls Gemini (primary). If Gemini raises anything at all -- a 429
    rate limit, a 503 server error, or any other exception -- catches it
    immediately, logs a warning, and falls back to Groq instead of crashing.
    Returns (text, engine_used) so callers can surface which one ran."""
    try:
        response = _generate_content_gemini(client, prompt)
        return response.text, "gemini"
    except Exception as exc:
        logger.warning(
            "Gemini request failed (%s: %s); falling back to Groq (%s).",
            type(exc).__name__, exc, GROQ_MODEL,
        )
        return _generate_content_groq(prompt), "groq"


def call_gemini_chef(city, path):
    """Sends the package to Gemini to generate the final itinerary output."""
    print(f"Calling Gemini to generate itinerary for {city}...")

    client = genai.Client()
    package_content = path.read_text(encoding="utf-8")

    prompt = f"""
    You are an expert travel concierge. Review the following planning package,
    which includes agent instructions and user requirements. Generate the final,
    fully detailed travel itinerary in clean Markdown format, covering exactly
    the number of days given by "Duration" in the User Requirements section
    below (not any other day count you may see elsewhere).

    {package_content}
    """

    itinerary_text, engine = _generate_content(client, prompt)

    # Append the AI-generated itinerary below the package block
    separator = "\n\n---\n\n## Generated Itinerary\n\n"
    updated_content = package_content + separator + itinerary_text
    path.write_text(updated_content, encoding="utf-8")
    print(f"Successfully populated itinerary in {path.name}! (engine: {engine})")


def slugify(city):
    slug = re.sub(r"[^a-z0-9]+", "_", city.strip().lower()).strip("_")
    return slug or "trip"


# Free-text city names that commonly refer to a destinations/ folder whose
# name doesn't match the slugified input directly.
CITY_ALIASES = {
    "new_york": "nyc",
    "new_york_city": "nyc",
    "cdmx": "mexico_city",
    "ciudad_de_mexico": "mexico_city",
}


def find_destination_city(city):
    """Best-effort match of a free-text destination to a destinations/
    folder, for the highlights RAG lookup below. Tries an exact slug match,
    then a known alias, then a fuzzy match; returns None if nothing is close
    enough (the app just skips local highlights in that case)."""
    cities = list_cities()
    slug = slugify(city)
    if slug in cities:
        return slug
    alias = CITY_ALIASES.get(slug)
    if alias in cities:
        return alias
    close = difflib.get_close_matches(slug, cities, n=1, cutoff=0.6)
    return close[0] if close else None


def read_city_highlights(city):
    """Curated local highlights for `city`, read from
    destinations/{city}/highlights.txt if that destination folder exists.
    This is the RAG step: it hands the model real local knowledge instead of
    letting it guess. Returns None if there's no matching folder or file."""
    match = find_destination_city(city)
    if not match:
        return None
    path = DESTINATIONS / match / "highlights.txt"
    if not path.is_file():
        return None
    return path.read_text(encoding="utf-8").strip()


def build_requirements_text(city, travelers, duration, budget, focus, must_haves=""):
    """Renders form inputs from the Streamlit app in the same shape as a
    destinations/*/must_haves.txt file, so it slots into the same prompt."""
    focus_str = ", ".join(focus) if isinstance(focus, (list, tuple)) else focus
    lines = [
        f"Destination: {city.strip()}",
        f"Duration: {duration} Days",
        f"Travelers: {travelers}",
        f"Budget Level: {budget}",
        f"Trip Focus: {focus_str}",
    ]
    if must_haves and must_haves.strip():
        lines += ["", "Must-See / Must-Do Activities:", must_haves.strip()]
    return "\n".join(lines)


def build_package_from_params(city, travelers, duration, budget, focus, must_haves=""):
    instructions = read_file(INSTRUCTIONS, "agent_instructions.md")
    requirements = build_requirements_text(city, travelers, duration, budget, focus, must_haves)
    highlights = read_city_highlights(city)
    title = city.strip().title()
    sections = [
        BEGIN,
        f"# Planning Package: {title}",
        "",
        "## 1. Agent Instructions",
        "",
        instructions,
        "",
        "## 2. User Requirements",
        "",
        "```text",
        requirements,
        "```",
    ]
    if highlights:
        sections += [
            "",
            "## 3. Local Highlights (reference knowledge)",
            "",
            f"Source: `destinations/{find_destination_city(city)}/highlights.txt`",
            "",
            "```text",
            highlights,
            "```",
        ]
    sections.append(END)
    return "\n".join(sections)


def generate_itinerary_from_params(city, travelers, duration, budget, focus, must_haves=""):
    """Builds a planning package straight from Streamlit form inputs (no
    destinations/{city}/must_haves.txt required), calls Gemini (falling back
    to Groq if Gemini errors out), saves the result to
    output/{city}_itinerary.md, and returns (markdown, saved_path, engine).
    """
    package = build_package_from_params(city, travelers, duration, budget, focus, must_haves)

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    path = OUTPUT_DIR / f"{slugify(city)}_itinerary.md"
    path.write_text(package + "\n", encoding="utf-8")

    client = genai.Client()
    prompt = f"""
    You are an expert travel concierge. Review the following planning package,
    which includes agent instructions and user requirements. Generate the final,
    fully detailed travel itinerary in clean Markdown format, covering exactly
    the number of days given by "Duration" in the User Requirements section
    below (not any other day count you may see elsewhere). Respect the Budget
    Level and Trip Focus constraints throughout the plan. Every item listed
    under "Must-See / Must-Do Activities" must be explicitly scheduled into a
    specific day and time block. If a "Local Highlights" section is present,
    treat it as trusted local knowledge and weave in the most relevant spots
    where they fit naturally -- don't just append them as a list.

    {package}
    """
    itinerary_text, engine = _generate_content(client, prompt)

    separator = "\n\n---\n\n## Generated Itinerary\n\n"
    path.write_text(package + separator + itinerary_text, encoding="utf-8")
    return itinerary_text, path, engine


def main():
    cities = list_cities()
    city = sys.argv[1] if len(sys.argv) > 1 else "mexico_city"
    if city not in cities:
        sys.exit(f"Unknown city '{city}'. Available: {', '.join(cities)}")

    # 1. Build and write the package
    action, path = write_package(city, build_package(city))
    print(f"{action} {path.name}")

    # 2. Hand it over to Gemini
    call_gemini_chef(city, path)


if __name__ == "__main__":
    main()